FROM mongo-express:0.54.0

# # Copiar wait-for-it.sh y entrypoint.sh al contenedor
# COPY wait-for-it.sh /wait-for-it.sh
# COPY entrypoint.sh /entrypoint.sh

# # Dar permisos de ejecución
# RUN chmod +x /wait-for-it.sh /entrypoint.sh

# # Establecer el entrypoint personalizado
# ENTRYPOINT ["/entrypoint.sh"]
