"""
Django settings for ms-main-load-data project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from celery.schedules import crontab
from .mongo_setup import connect_mongo
import os
import environ
import mongoengine
import warnings 



DEBUG = True

env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1hh=deea+j$skklj#g%n)f0f3l=)%no&9qv+&r9j-p+%1o8$tu'

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1',
]

CSRF_TRUSTED_ORIGINS = [
    'https://localhost',
    'https://127.0.0.1',
    'https://127.0.0.1:444',
]

CSRF_COOKIE_SECURE = False  

CSRF_COOKIE_NAME = 'csrftoken'

CSRF_COOKIE_HTTPONLY = False

CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

CSRF_COOKIE_SAMESITE = 'Lax'

SESSION_COOKIE_SECURE = False  

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "https://localhost",
    "https://127.0.0.1",
    "https://127.0.0.1:444",
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'Authorization',
    'Content-Type',
    'Accept',
    'x-requested-with',
    'accept',
    'origin',
    'user-agent',
    'dnt',
    'cache-control',
    'X-CSRFToken',
    'x-requested-with',
    'x-xsrf-token',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'rest_framework',
    'rest_framework_mongoengine',
    'ms_app_manage_auth',
    'ms_load_from_zoho',
    'ms_load_sequence_tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    'ms_app_manage_auth.middleware.MongoAuthMiddleware',
    'ms_app_manage_auth.middleware.MongoConnectionMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'ms_app_manage_auth.backends.MongoDBBackend',
    # 'django.contrib.auth.backends.ModelBackend',
]

# AUTH_USER_MODEL = 'ms_app_manage_auth.CustomUser'

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

ROOT_URLCONF = 'ms_main_load_data.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ms_main_load_data.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': f'{env('POSTGRES_DB_ENGINE', default="django.db.backends.postgresql_psycopg2")}',
        'NAME': f'{env('POSTGRES_DB_NAME', default="")}',
        'USER': f'{env('POSRGRES_DB_USER', default="")}',
        'PASSWORD': f'{env('POSTGRES_DB_PASSWORD', default="")}',
        'HOST': f'{env('POSTGRES_DB_HOST', default="")}',
        'PORT': f'{env('POSTGRES_DB_PORT', default="")}',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# REST FRAMEWORK

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'ms_app_manage_auth.authentication.MongoTokenAuthentication',  
#     ],
# }


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
BASE_DIR_STATIC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKUP_DIR = os.path.join(BASE_DIR, 'backup')

MEDIA_URL = '/backup/'
MEDIA_ROOT = BACKUP_DIR

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST FRAMEWORK

FRONTEND_URL = env('FRONTEND_URL', default='https://127.0.0.1/')

# Celery

CELERY_BROKER_URL = 'redis://redis_main_load_data:6379/0'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_RESULT_BACKEND = 'redis://redis_main_load_data:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/New_York'
CELERY_ENABLE_UTC = False

# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# CELERY_BEAT_SCHEDULE = {
#     # Lunes a Sábado
#     'run-task-sequence-every-30-min-mon-sat': {
#         'task': 'ms_load_sequence_tasks.tasks.task_sequence_30_min',
#         'schedule': crontab(minute='*/2', hour='7-17', day_of_week='mon-sat'),
#     },

#     # Domingo
#     'run-task-sequence-every-2-hours-sun-30-min': {
#         'task': 'ms_load_sequence_tasks.tasks.task_sequence_30_min',
#         'schedule': crontab(minute=0, hour='*/2', day_of_week='sun'),
#     },
    
# }

# MONGOENGINE

warnings.filterwarnings("ignore", message="MongoClient opened before fork")

MONGO_HOST = env('MONGO_HOST', default='localhost')
MONGO_PORT = int(env('MONGO_PORT', default=27017))
MONGO_USER = env('MONGO_USER', default='root')
MONGO_PASSWORD = env('MONGO_PASSWORD', default='')
MONGO_DB = env('MONGO_DB', default='')
MONGO_URI = env('MONGO_URI', default='')

connect_mongo()

# ZOHO

ZOHO_SCOPES = env.list('ZOHO_SCOPES', default=[])
ZOHO_TOKEN_URL = env('ZOHO_TOKEN_URL', default='')
ZOHO_AUTH_URL = env('ZOHO_AUTH_URL', default='')
ZOHO_INVENTORY_ITEMS_URL = env('ZOHO_INVENTORY_ITEMS_URL', default='')
ZOHO_INVENTORY_SHIPMENTORDERS_URL = env('ZOHO_INVENTORY_SHIPMENTORDERS_URL', default='')
ZOHO_INVENTORY_PURCHASERECEIVES_URL = env('ZOHO_INVENTORY_PURCHASERECEIVES_URL', default='')
ZOHO_INVENTORY_SALESORDERS_URL = env('ZOHO_INVENTORY_SALESORDERS_URL', default='')
ZOHO_INVENTORY_SHIPMENTS_URL = env('ZOHO_INVENTORY_SHIPMENTS_URL', default='')
ZOHO_INVENTORY_PACKAGES_URL = env('ZOHO_INVENTORY_PACKAGES_URL', default='')
ZOHO_BOOKS_INVOICES_URL = env('ZOHO_BOOKS_INVOICES_URL', default='')
ZOHO_BOOKS_CUSTOMERS_URL = env('ZOHO_BOOKS_CUSTOMERS_URL', default='')
ZOHO_BOOKS_ITEMS_URL = env('ZOHO_BOOKS_ITEMS_URL', default='')