"""
Django settings for ms-main-load-data project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
from .mongo_setup import (
    connect_mongo_dev
)
import os
import environ
import warnings 
import logging

logger = logging.getLogger(__name__)



# DEBUG = True

BASE_DIR = Path(__file__).resolve().parent.parent  # .../ms_main_load_data
env = environ.Env()

# .env en la raíz del repo: .../app/.env
env_file = BASE_DIR.parent / ".env"
if env_file.exists():
    environ.Env.read_env(str(env_file))
else:
    # Log amigable, sin ruido
    import logging
    logging.getLogger(__name__).warning(
        "No .env at %s (ok if you inject env via Docker)", env_file
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1hh=deea+j$skklj#g%n)f0f3l=)%no&9qv+&r9j-p+%1o8$tu'

# SECURITY WARNING: don't run with debug turned on in production!

# LOGGING

# settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/log/celery.log',
            'formatter': 'verbose',
        },
        'null': {
            'class': 'logging.NullHandler',
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s %(name)s:%(lineno)d %(message)s'
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    'loggers': {
        "ms_load_from_zoho": {
            "handlers": ["console"],
            "level": "INFO",            # cambia a DEBUG si quieres
            "propagate": False,         # evita doble log
        },
        "urllib3": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'pymongo': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'pymongo.command': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'pymongo.connection': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'pymongo.serverSelection': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
# ENVIRONMENT = env('ENVIRONMENT', default='DEV')

# if ENVIRONMENT == 'DEV':
#     DEBUG = True
#     ALLOWED_HOSTS = ['*']
# else:
#     DEBUG = False
#     ALLOWED_HOST_REGEXES = [
#         "regex:^172\\.31\\.\\d+\\.\\d+(:\\d+)?$",
#         "regex:^10\\.0\\.\\d+\\.\\d+(:\\d+)?$"
#     ]
#     ALLOWED_HOSTS.extend(ALLOWED_HOST_REGEXES)
    
# print(f'ALLOWED_HOSTS: {ALLOWED_HOSTS}')

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

CSRF_COOKIE_SECURE = False  

CSRF_COOKIE_NAME = 'csrftoken'

CSRF_COOKIE_HTTPONLY = False

CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

CSRF_COOKIE_SAMESITE = 'Lax'

SESSION_COOKIE_SECURE = False  

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'Authorization',
    'Content-Type',
    'Accept',
    'x-requested-with',
    'accept',
    'origin',
    'user-agent',
    'dnt',
    'cache-control',
    'X-CSRFToken',
    'x-requested-with',
    'x-xsrf-token',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'rest_framework',
    'rest_framework_mongoengine',
    'ms_app_manage_auth',
    'ms_load_from_zoho',
    'ms_load_from_senitron',
    'ms_load_sequence_tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    'ms_app_manage_auth.middleware.MongoAuthMiddleware',
    'ms_app_manage_auth.middleware.MongoConnectionMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'ms_app_manage_auth.backends.MongoDBBackend',
    # 'django.contrib.auth.backends.ModelBackend',
]

# AUTH_USER_MODEL = 'ms_app_manage_auth.CustomUser'

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

ROOT_URLCONF = 'ms_main_load_data.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ms_main_load_data.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': f'{env('POSTGRES_DB_ENGINE', default="django.db.backends.postgresql_psycopg2")}',
#         'NAME': f'{env('POSTGRES_DB_NAME', default="")}',
#         'USER': f'{env('POSRGRES_DB_USER', default="")}',
#         'PASSWORD': f'{env('POSTGRES_DB_PASSWORD', default="")}',
#         'HOST': f'{env('POSTGRES_DB_HOST', default="")}',
#         'PORT': f'{env('POSTGRES_DB_PORT', default="")}',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# REST FRAMEWORK

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'ms_app_manage_auth.authentication.MongoTokenAuthentication',  
#     ],
# }


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
BASE_DIR_STATIC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKUP_DIR = os.path.join(BASE_DIR, 'backup')

MEDIA_URL = '/backup/'
MEDIA_ROOT = BACKUP_DIR

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST FRAMEWORK

FRONTEND_URL = env('FRONTEND_URL', default='')

# ZOHO ORG ID

ZOHO_ORG_ID_NWSHOME = env('ZOHO_ORG_ID_NWSHOME', default='')
ZOHO_ORG_ID = env('ZOHO_ORG_ID', default='')
TIMEDELTA_ZOHO_SHIPMENTS = env.int('TIMEDELTA_ZOHO_SHIPMENTS', default=1)
TIMEDELTA_ZOHO_SALES_ORDERS = env.int('TIMEDELTA_ZOHO_SALES_ORDERS', default=1)
TIMEDELTA_ZOHO_SALES_ORDERS_NWSHOMES = env.int('TIMEDELTA_ZOHO_SALES_ORDERS_NWSHOMES', default=1)
TIMEDELTA_ZOHO_INVOICES = env.int('TIMEDELTA_ZOHO_INVOICES', default=1)
TIMEDELTA_ZOHO_CUSTOMERS = env.int('TIMEDELTA_ZOHO_CUSTOMERS', default=1)
TIMEDELTA_ZOHO_ITEMS = env.int('TIMEDELTA_ZOHO_ITEMS', default=1)
TIMEDELTA_ZOHO_PURCHASE_ORDERS = env.int('TIMEDELTA_ZOHO_PURCHASE_ORDERS', default=0)

# Celery

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='')
CELERY_TASK_IGNORE_RESULT = False
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_EXPIRES = 86400  # 24h, evita que expire antes de encadenar

from kombu import Queue, Exchange
CELERY_TASK_DEFAULT_QUEUE = "zoho_shipments"  # <- evita default_queue=None
CELERY_TASK_QUEUES = (
    Queue("zoho_shipments",     Exchange("zoho_shipments",     type="direct"), routing_key="zoho_shipments"),
    Queue("zoho_catalog",       Exchange("zoho_catalog",       type="direct"), routing_key="zoho_catalog"),
    Queue("zoho_sales",         Exchange("zoho_sales",         type="direct"), routing_key="zoho_sales"),
    Queue("zoho_purchases",     Exchange("zoho_purchases",     type="direct"), routing_key="zoho_purchases"),
    Queue("senitron",           Exchange("senitron",           type="direct"), routing_key="senitron"),
    # opcional: Queue("default", Exchange("default", type="direct"), routing_key="default"),
)

CELERY_TASK_ROUTES = {
    # ZOHO
    "ms_load_from_zoho.tasks.task_load_inventory_sales_orders": {
        "queue": "zoho_sales", 
        "routing_key": "zoho_sales"
    },
    "ms_load_from_zoho.tasks.task_load_books_invoices":         {
        "queue": "zoho_sales", 
        "routing_key": "zoho_sales"
    },
    "ms_load_from_zoho.tasks.task_load_books_customers":        {
        "queue": "zoho_catalog", 
        "routing_key": "zoho_catalog"
    },
    "ms_load_from_zoho.tasks.task_load_inventory_items":        {
        "queue": "zoho_catalog", 
        "routing_key": "zoho_catalog"
    },
    "ms_load_from_zoho.tasks.task_load_inventory_shipments":    {
        "queue": "zoho_shipments", 
        "routing_key": "zoho_shipments"
    },
    "ms_load_from_zoho.tasks.task_load_inventory_purchaseorders": {
        "queue": "zoho_purchases",
        "routing_key": "zoho_purchases"
    },
    "ms_load_from_zoho.tasks.task_load_inventory_itemgroups": {
        "queue": "zoho_catalog",
        "routing_key": "zoho_catalog"
    },
    "ms_load_from_zoho.tasks.task_update_fields_items": {
        "queue": "zoho_catalog",
        "routing_key": "zoho_catalog"
    },
    
    # SENITRON
    "ms_load_from_senitron.tasks.task_load_senitron_items_assets": {
        "queue": "senitron",
        "routing_key": "senitron"
    },
    "ms_load_from_senitron.tasks.task_load_senitron_items_assets_logs": {
        "queue": "senitron",
        "routing_key": "senitron"
    },

    # SEQUENCE TASKS
    ## ZOHO
    "ms_load_sequence_tasks.tasks.task_sequence_by_zoho_shipments": {
        "queue": "zoho_shipments",
        "routing_key": "zoho_shipments"
    },
    "ms_load_sequence_tasks.tasks.task_sequence_by_zoho_sales": {
        "queue": "zoho_sales",
        "routing_key": "zoho_sales"
    },
    "ms_load_sequence_tasks.tasks.task_sequence_by_zoho_customers_items": {
        "queue": "zoho_catalog",
        "routing_key": "zoho_catalog"
    },
    "ms_load_sequence_tasks.tasks.task_sequence_by_zoho_itemgroups": {
        "queue": "zoho_catalog",
        "routing_key": "zoho_catalog"
    },
    "ms_load_sequence_tasks.tasks.task_sequence_by_zoho_purchases": {
        "queue": "zoho_purchases",
        "routing_key": "zoho_purchases"
    },
    ## SENITRON
    "ms_load_sequence_tasks.tasks.task_sequence_by_senitron": {
        "queue": "senitron",
        "routing_key": "senitron"
    },
    ## TINY ZOHO
    "ms_load_sequence_tasks.tasks.tiny_sleep_zoho_shipments": {
        "queue": "zoho_shipments",
        "routing_key": "zoho_shipments"
    },
    "ms_load_sequence_tasks.tasks.tiny_sleep_zoho_sales": {
        "queue": "zoho_sales",
        "routing_key": "zoho_sales"
    },
    "ms_load_sequence_tasks.tasks.tiny_sleep_zoho_catalog": {
        "queue": "zoho_catalog",
        "routing_key": "zoho_catalog"
    },
    "ms_load_sequence_tasks.tasks.tiny_sleep_zoho_purchases": {
        "queue": "zoho_purchases",
        "routing_key": "zoho_purchases"
    },
    ## TINY SENITRON
    "ms_load_sequence_tasks.tasks.tiny_sleep_senitron": {
        "queue": "senitron",
        "routing_key": "senitron"
    },
    
    
}
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/New_York'
CELERY_ENABLE_UTC = False
CELERY_WORKER_PREFETCH_MULTIPLIER = 1        # importante
CELERY_TASK_ACKS_LATE = True                 # reconoce al finalizar
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 7200}

# --- Límites de tiempo por defecto (puedes afinarlos por tarea) ---
CELERY_TASK_TIME_LIMIT = 900                 # hard kill 15 min
CELERY_TASK_SOFT_TIME_LIMIT = 840            # aviso a los 14 min

# --- Rate limit sólo para shipments (reduce 429) ---
CELERY_TASK_ANNOTATIONS = {
    # catálogos suelen ser voluminosos pero menos sensibles
    'ms_load_from_zoho.tasks.task_load_books_customers': {'rate_limit': '6/m'},   # 1 cada 10s
    'ms_load_from_zoho.tasks.task_load_inventory_items': {'rate_limit': '6/m'},
    'ms_load_from_zoho.tasks.task_load_inventory_itemgroups': {'rate_limit': '4/m'},
    'ms_load_from_zoho.tasks.task_update_fields_items': {'rate_limit': '6/m'},

    # ventas
    'ms_load_from_zoho.tasks.task_load_inventory_sales_orders': {'rate_limit': '6/m'},
    'ms_load_from_zoho.tasks.task_load_books_invoices':        {'rate_limit': '6/m'},

    # shipments (detalles ya van serializados en tu service)
    'ms_load_from_zoho.tasks.task_load_inventory_shipments':   {'rate_limit': '4/m'},
    
    # purchases
    'ms_load_from_zoho.tasks.task_load_inventory_purchaseorders':   {'rate_limit': '6/m'},
}

# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# CELERY_BEAT
DAY_OF_WEEK_MONDAY_TO_SATURDAY = env('DAY_OF_WEEK_MONDAY_TO_SATURDAY', default='mon-sat')
DAY_OF_WEEK_SUNDAY = env('DAY_OF_WEEK_SUNDAY', default='sun')
HOUR_MONDAY_TO_SATURDAY = env('HOUR_MONDAY_TO_SATURDAY', default='7-17')
HOUR_SUNDAY = env('HOUR_SUNDAY', default='*/6')

# CELERY_BEAT ZOHO SCHEDULES
MINUTE_ZOHO_SALES = env('MINUTE_ZOHO_SALES', default='6,16,26,36,46,56')
MINUTE_ZOHO_ITEMGROUPS = env('MINUTE_ZOHO_ITEMGROUPS', default='5')
MINUTE_ZOHO_CATALOG = env('MINUTE_ZOHO_CATALOG', default='9,19,29,39,49,59')
MINUTE_ZOHO_SHIPMENTS = env('MINUTE_ZOHO_SHIPMENTS', default='3,13,23,33,43,53')
MINUTE_ZOHO_PURCHASES = env('MINUTE_ZOHO_PURCHASES', default='0,10,20,30,40,50')

CRONTAB_ZOHO_ITEMS_UPDATE_FIELDS = crontab(
    minute='0,5,10,15,20,25,30,35,40,45,50,55',
    hour='*/1',
    day_of_week=DAY_OF_WEEK_MONDAY_TO_SATURDAY
)

# # SALES
CRONTAB_ZOHO_SALES_MONDAY_TO_SATURDAY = crontab(
    minute=MINUTE_ZOHO_SALES, 
    hour=HOUR_MONDAY_TO_SATURDAY, 
    day_of_week=DAY_OF_WEEK_MONDAY_TO_SATURDAY
)

CRONTAB_ZOHO_SALES_SUNDAY = crontab(
    minute=MINUTE_ZOHO_SALES,
    hour=HOUR_SUNDAY,
    day_of_week=DAY_OF_WEEK_SUNDAY
)

# # CUSTOMERS, ITEMS (CATALOG)
CRONTAB_ZOHO_CATALOG_MONDAY_TO_SATURDAY = crontab(
    minute=MINUTE_ZOHO_CATALOG,
    hour=HOUR_MONDAY_TO_SATURDAY,
    day_of_week=DAY_OF_WEEK_MONDAY_TO_SATURDAY
)

CRONTAB_ZOHO_CATALOG_SUNDAY = crontab(
    minute=MINUTE_ZOHO_CATALOG,
    hour=HOUR_SUNDAY,
    day_of_week=DAY_OF_WEEK_SUNDAY
)

# # ITEMGROUPS (CATALOG)
CRONTAB_ZOHO_ITEMGROUPS_MONDAY_TO_SATURDAY = crontab(
    minute=MINUTE_ZOHO_ITEMGROUPS,
    hour='*/1',
    day_of_week=DAY_OF_WEEK_MONDAY_TO_SATURDAY
)

CRONTAB_ZOHO_ITEMGROUPS_SUNDAY = crontab(
    minute=MINUTE_ZOHO_ITEMGROUPS,
    hour=HOUR_SUNDAY,
    day_of_week=DAY_OF_WEEK_SUNDAY
)

# # SHIPMENTS
CRONTAB_ZOHO_SHIPMENTS_MONDAY_TO_SATURDAY = crontab(
    minute=MINUTE_ZOHO_SHIPMENTS,
    hour=HOUR_MONDAY_TO_SATURDAY,
    day_of_week=DAY_OF_WEEK_MONDAY_TO_SATURDAY
)

CRONTAB_ZOHO_SHIPMENTS_SUNDAY = crontab(
    minute=MINUTE_ZOHO_SHIPMENTS,
    hour=HOUR_SUNDAY,
    day_of_week=DAY_OF_WEEK_SUNDAY
)

# # PURCHASES
CRONTAB_ZOHO_PURCHASES_MONDAY_TO_SATURDAY = crontab(
    minute=MINUTE_ZOHO_PURCHASES,
    hour=HOUR_MONDAY_TO_SATURDAY,
    day_of_week=DAY_OF_WEEK_MONDAY_TO_SATURDAY
)

CRONTAB_ZOHO_PURCHASES_SUNDAY = crontab(
    minute=MINUTE_ZOHO_PURCHASES,
    hour=HOUR_SUNDAY,
    day_of_week=DAY_OF_WEEK_SUNDAY
)

# SENITRON
MINUTE_SENITRON = env('MINUTE_SENITRON', default='1,11,21,31,41,51')

CRONTAB_SENITRON_MONDAY_TO_SATURDAY = crontab(
    minute=MINUTE_SENITRON,
    hour=HOUR_MONDAY_TO_SATURDAY,
    day_of_week=DAY_OF_WEEK_MONDAY_TO_SATURDAY
)

CRONTAB_SENITRON_SUNDAY = crontab(
    minute=MINUTE_SENITRON,
    hour=HOUR_SUNDAY,
    day_of_week=DAY_OF_WEEK_SUNDAY
)

# SCHEDULES
CELERY_BEAT_SCHEDULE = {
    # MONDAY_TO_SATURDAY
    # 'run-task-items-update-fields-monday-saturday': {
    #     'task': 'ms_load_from_zoho.tasks.task_update_fields_items',
    #     'schedule': CRONTAB_ZOHO_ITEMS_UPDATE_FIELDS,
    #     'options': {'queue': 'zoho_catalog'},
    # },
    'run-task-sequence-zoho-customers-items-monday-saturday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_zoho_customers_items',
        'schedule': CRONTAB_ZOHO_CATALOG_MONDAY_TO_SATURDAY,
        'options': {'queue': 'zoho_catalog'},        # <-- importante
    },
    'run-task-sequence-zoho-itemgroups-monday-saturday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_zoho_itemgroups',
        'schedule': CRONTAB_ZOHO_ITEMGROUPS_MONDAY_TO_SATURDAY,
        'options': {'queue': 'zoho_catalog'},        # <-- importante
    },
    'run-task-sequence-zoho-sales-monday-saturday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_zoho_sales',
        'schedule': CRONTAB_ZOHO_SALES_MONDAY_TO_SATURDAY,
        'options': {'queue': 'zoho_sales'},        # <-- importante
    },
    'run-task-sequence-zoho-shipments-monday-saturday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_zoho_shipments',
        'schedule': CRONTAB_ZOHO_SALES_MONDAY_TO_SATURDAY,
        'options': {'queue': 'zoho_shipments'},        # <-- importante
    },
    'run-task-sequence-senitron-monday-saturday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_senitron',
        'schedule': CRONTAB_SENITRON_MONDAY_TO_SATURDAY,
        'options': {'queue': 'senitron'},    # <-- importante
    },
    'run-task-sequence-zoho-purchases-monday-saturday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_zoho_purchases',
        'schedule': CRONTAB_ZOHO_PURCHASES_MONDAY_TO_SATURDAY,
        'options': {'queue': 'zoho_purchases'},        # <-- importante
    },

    # SUNDAY
    'run-task-sequence-zoho-customers-items-sunday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_zoho_customers_items',
        'schedule': CRONTAB_ZOHO_CATALOG_SUNDAY,
        'options': {'queue': 'zoho_catalog'},
    },
    'run-task-sequence-zoho-itemgroups-sunday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_zoho_itemgroups',
        'schedule': CRONTAB_ZOHO_ITEMGROUPS_SUNDAY,
        'options': {'queue': 'zoho_catalog'},        # <-- importante
    },
    'run-task-sequence-zoho-sales-sunday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_zoho_sales',
        'schedule': CRONTAB_ZOHO_SALES_SUNDAY,
        'options': {'queue': 'zoho_sales'},        # <-- importante
    },
    'run-task-sequence-zoho-shipments-sunday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_zoho_shipments',
        'schedule': CRONTAB_ZOHO_SHIPMENTS_SUNDAY,
        'options': {'queue': 'zoho_shipments'},        # <-- importante
    },
    'run-task-sequence-senitron-sunday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_senitron',
        'schedule': CRONTAB_SENITRON_SUNDAY,
        'options': {'queue': 'senitron'},
    },
    'run-task-sequence-zoho-purchases-sunday': {
        'task': 'ms_load_sequence_tasks.tasks.task_sequence_by_zoho_purchases',
        'schedule': CRONTAB_ZOHO_PURCHASES_SUNDAY,
        'options': {'queue': 'zoho_purchases'},        # <-- importante
    },
}

# MONGOENGINE

warnings.filterwarnings("ignore", message="MongoClient opened before fork")

MONGO_HOST = env('MONGO_HOST', default='localhost')
MONGO_PORT = int(env('MONGO_PORT', default=27017))
MONGO_USER = env('MONGO_USER', default='root')
MONGO_PASSWORD = env('MONGO_PASSWORD', default='')
MONGO_DB = env('MONGO_DB', default='')
connect_mongo_dev()
# MONGO_URI = env('MONGO_URI', default='') if ENVIRONMENT == 'DEV' else (
#     f"mongodb://{urllib.parse.quote(MONGO_USER)}:{urllib.parse.quote(MONGO_PASSWORD)}"
#     f"@{MONGO_HOST}:{MONGO_PORT}/{MONGO_DB}?ssl=true&retryWrites=false"
# )

# if ENVIRONMENT == 'DEV':
#     connect_mongo_dev()
# else:
#     connect_mongo_prod()

# ZOHO

ZOHO_SCOPES = env.list('ZOHO_SCOPES', default=[])
ZOHO_TOKEN_URL = env('ZOHO_TOKEN_URL', default='')
ZOHO_AUTH_URL = env('ZOHO_AUTH_URL', default='')
ZOHO_INVENTORY_ITEMS_URL = env('ZOHO_INVENTORY_ITEMS_URL', default='')
ZOHO_INVENTORY_ITEMGROUPS_URL = env('ZOHO_INVENTORY_ITEMGROUPS_URL', default='')
ZOHO_INVENTORY_SHIPMENTORDERS_URL = env('ZOHO_INVENTORY_SHIPMENTORDERS_URL', default='')
ZOHO_INVENTORY_PURCHASEORDERS_URL = env('ZOHO_INVENTORY_PURCHASEORDERS_URL', default='')
ZOHO_INVENTORY_PURCHASERECEIVES_URL = env('ZOHO_INVENTORY_PURCHASERECEIVES_URL', default='')
ZOHO_INVENTORY_SALESORDERS_URL = env('ZOHO_INVENTORY_SALESORDERS_URL', default='')
ZOHO_INVENTORY_SHIPMENTS_URL = env('ZOHO_INVENTORY_SHIPMENTS_URL', default='')
ZOHO_INVENTORY_PACKAGES_URL = env('ZOHO_INVENTORY_PACKAGES_URL', default='')
ZOHO_BOOKS_INVOICES_URL = env('ZOHO_BOOKS_INVOICES_URL', default='')
ZOHO_BOOKS_CUSTOMERS_URL = env('ZOHO_BOOKS_CUSTOMERS_URL', default='')
ZOHO_BOOKS_ITEMS_URL = env('ZOHO_BOOKS_ITEMS_URL', default='')

# SENITRON
API_KEY_SENITRON = env('API_KEY_SENITRON', default='')
API_SENITRON_QUANTITIES_URL = env('API_SENITRON_QUANTITIES_URL', default='')
API_SENITRON_ASSETS_URL = env('API_SENITRON_ASSETS_URL', default='')
API_SENITRON_ASSETS_LOGS_URL = env('API_SENITRON_ASSETS_LOGS_URL', default='')